name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: LCW Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.LCW_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.LCW_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: LCW Login to Amazon ECR
      id: login-ecr1
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: LCW Build, tag, and push docker image to Amazon ECR
      env: 
        REGISTRY: ${{ steps.login-ecr1.outputs.registry }}
        REPOSITORY: helloworld-was
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
    - name: LSJ Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.LSJ_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.LSJ_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: LSJ Login to Amazon ECR
      id: login-ecr2
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: LSJ Build, tag, and push docker image to Amazon ECR
      env: 
        REGISTRY: ${{ steps.login-ecr2.outputs.registry }}
        REPOSITORY: helloworld-was
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      
    - name: KKH Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.KKH_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.KKH_AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: KKH Login to Amazon ECR
      id: login-ecr3
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: KKH Build, tag, and push docker image to Amazon ECR
      env: 
        REGISTRY: ${{ steps.login-ecr3.outputs.registry }}
        REPOSITORY: helloworld-was
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
